# Generated by Django 5.0.6 on 2024-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mileage", models.PositiveIntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("preventative", "Preventative"),
                        ],
                        max_length=15,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
